-- List of world's countries from ISO 3166-1.
-- The ISO 3166-1-alpha-2 code is from http://www.iso.org/iso/prods-services/iso3166ma/02iso-3166-code-lists/country_names_and_code_elements .
-- The ISO alpha-3 code is from http://unstats.un.org/unsd/methods/m49/m49alpha.htm
-- The list of countries which do not use the metric system is from http://en.wikipedia.org/wiki/International_System_of_Units
-- Date ordering from http://en.wikipedia.org/wiki/Date_format_by_country

CREATE TABLE countries (
  name varchar(50) NOT NULL,
  iso2 varchar(2) NOT NULL PRIMARY KEY,
  iso3 varchar(3) NOT NULL,
  msystem char(1) NOT NULL DEFAULT 'M',         -- Metric system: M for Metric, I for imperial
  dformat char(3) NOT NULL DEFAULT 'DMY',       -- Date format: DMY or MDY or YMD
  tformat char(2) NOT NULL DEFAULT '24'         -- Time format: 24 or 12
);

INSERT INTO countries VALUES ('Andorra', 'ad', 'and', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('United Arab Emirates', 'ae', 'are', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Afghanistan', 'af', 'afg', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Antigua and Barbuda', 'ag', 'atg', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Anguilla', 'ai', 'aia', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Albania', 'al', 'alb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Armenia', 'am', 'arm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Angola', 'ao', 'ago', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Antarctica', 'aq', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Argentina', 'ar', 'arg', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('American Samoa', 'as', 'asm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Austria', 'at', 'aut', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Australia', 'au', 'aus', 'M', 'DMY', '12');
INSERT INTO countries VALUES ('Aruba', 'aw', 'abw', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Aland Islands', 'ax', 'ala', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Azerbaijan', 'az', 'aze', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bosnia and Herzegovina', 'ba', 'bih', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Barbados', 'bb', 'brb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bangladesh', 'bd', 'bgd', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Belgium', 'be', 'bel', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Burkina Faso', 'bf', 'bfa', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bulgaria', 'bg', 'bgr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bahrain', 'bh', 'bhr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Burundi', 'bi', 'bdi', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Benin', 'bj', 'ben', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saint Barthelemy', 'bl', 'blm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bermuda', 'bm', 'bmu', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Brunei Darussalam', 'bn', 'brn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bolivia, Plurinational State of', 'bo', 'bol', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bonaire, Sint Eustatius and Saba', 'bq', 'bes', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Brazil', 'br', 'bra', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bahamas', 'bs', 'bhs', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bhutan', 'bt', 'btn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Bouvet Island', 'bv', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Botswana', 'bw', 'bwa', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Belarus', 'by', 'blr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Belize', 'bz', 'blz', 'M', 'MDY', '12');
INSERT INTO countries VALUES ('Canada', 'ca', 'can', 'M', 'DMY', '12');
INSERT INTO countries VALUES ('Cocos (Keeling) Islands', 'cc', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Congo, The Democratic Republic of the', 'cd', 'cod', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Central African Republic', 'cf', 'caf', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Congo', 'cg', 'cog', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Switzerland', 'ch', 'che', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cote d''Ivoire', 'ci', 'civ', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cook Islands', 'ck', 'cok', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Chile', 'cl', 'chl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cameroon', 'cm', 'cmr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('China', 'cn', 'chn', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Colombia', 'co', 'col', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Costa Rica', 'cr', 'cri', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cuba', 'cu', 'cub', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cape Verde', 'cv', 'cpv', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Curacao', 'cw', 'cuw', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Christmas Island', 'cx', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cyprus', 'cy', 'cyp', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Czech Republic', 'cz', 'cze', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Germany', 'de', 'deu', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Djibouti', 'dj', 'dji', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Denmark', 'dk', 'dnk', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Dominica', 'dm', 'dma', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Dominican Republic', 'do', 'dom', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Algeria', 'dz', 'dza', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Ecuador', 'ec', 'ecu', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Estonia', 'ee', 'est', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Egypt', 'eg', 'egy', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Western Sahara', 'eh', 'esh', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Eritrea', 'er', 'eri', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Spain', 'es', 'esp', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Ethiopia', 'et', 'eth', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Finland', 'fi', 'fin', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Fiji', 'fj', 'fji', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Falkland Islands (Malvinas)', 'fk', 'flk', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Micronesia, Federated States of', 'fm', 'fsm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Faroe Islands', 'fo', 'fro', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('France', 'fr', 'fra', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Gabon', 'ga', 'gab', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('United Kingdom', 'gb', 'gbr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Grenada', 'gd', 'grd', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Georgia', 'ge', 'geo', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('French Guiana', 'gf', 'guf', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Guernsey', 'gg', 'ggy', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Ghana', 'gh', 'gha', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Gibraltar', 'gi', 'gib', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Greenland', 'gl', 'grl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Gambia', 'gm', 'gmb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Guinea', 'gn', 'gin', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Guadeloupe', 'gp', 'glp', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Equatorial Guinea', 'gq', 'gnq', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Greece', 'gr', 'grc', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('South Georgia and The South Sandwich Islands', 'gs', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Guatemala', 'gt', 'gtm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Guam', 'gu', 'gum', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Guinea-Bissau', 'gw', 'gnb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Guyana', 'gy', 'guy', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Hong Kong', 'hk', 'hkg', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Heard Island and McDonald Islands', 'hm', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Honduras', 'hn', 'hnd', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Croatia', 'hr', 'hrv', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Haiti', 'ht', 'hti', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Hungary', 'hu', 'hun', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Indonesia', 'id', 'idn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Ireland', 'ie', 'irl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Israel', 'il', 'isr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Isle of Man', 'im', 'imn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('India', 'in', 'ind', 'M', 'DMY', '12');
INSERT INTO countries VALUES ('British Indian Ocean Territory', 'io', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Iraq', 'iq', 'irq', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Iran, Islamic Republic of', 'ir', 'irn', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Iceland', 'is', 'isl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Italy', 'it', 'ita', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Jersey', 'je', 'jey', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Jamaica', 'jm', 'jam', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Jordan', 'jo', 'jor', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Japan', 'jp', 'jpn', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Kenya', 'ke', 'ken', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Kyrgyzstan', 'kg', 'kgz', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cambodia', 'kh', 'khm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Kiribati', 'ki', 'kir', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Comoros', 'km', 'com', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saint Kitts and Nevis', 'kn', 'kna', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Korea, Democratic People''s Republic of', 'kp', 'prk', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Korea, Republic of', 'kr', 'kor', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Kuwait', 'kw', 'kwt', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Cayman Islands', 'ky', 'cym', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Kazakhstan', 'kz', 'kaz', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Lao People''s Democratic Republic', 'la', 'lao', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Lebanon', 'lb', 'lbn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saint Lucia', 'lc', 'lca', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Liechtenstein', 'li', 'lie', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Sri Lanka', 'lk', 'lka', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Liberia', 'lr', 'lbr', 'I', 'DMY', '24');
INSERT INTO countries VALUES ('Lesotho', 'ls', 'lso', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Lithuania', 'lt', 'ltu', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Luxembourg', 'lu', 'lux', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Latvia', 'lv', 'lva', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Libyan Arab Jamahiriya', 'ly', 'lby', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Morocco', 'ma', 'mar', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Monaco', 'mc', 'mco', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Moldova, Republic of', 'md', 'mda', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Montenegro', 'me', 'mne', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saint Martin (French Part)', 'mf', 'maf', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Madagascar', 'mg', 'mdg', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Marshall Islands', 'mh', 'mhl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Macedonia, The former Yugoslav Republic of', 'mk', 'mkd', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Mali', 'ml', 'mli', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Myanmar', 'mm', 'mmr', 'I', 'DMY', '24');
INSERT INTO countries VALUES ('Mongolia', 'mn', 'mng', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Macao', 'mo', 'mac', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Northern Mariana Islands', 'mp', 'mnp', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Martinique', 'mq', 'mtq', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Mauritania', 'mr', 'mrt', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Montserrat', 'ms', 'msr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Malta', 'mt', 'mlt', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Mauritius', 'mu', 'mus', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Maldives', 'mv', 'mdv', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Malawi', 'mw', 'mwi', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Mexico', 'mx', 'mex', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Malaysia', 'my', 'mys', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Mozambique', 'mz', 'moz', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Namibia', 'na', 'nam', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('New Caledonia', 'nc', 'ncl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Niger', 'ne', 'ner', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Norfolk Island', 'nf', 'nfk', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Nigeria', 'ng', 'nga', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Nicaragua', 'ni', 'nic', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Netherlands', 'nl', 'nld', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Norway', 'no', 'nor', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Nepal', 'np', 'npl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Nauru', 'nr', 'nru', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Niue', 'nu', 'niu', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('New Zealand', 'nz', 'nzl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Oman', 'om', 'omn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Panama', 'pa', 'pan', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Peru', 'pe', 'per', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('French Polynesia', 'pf', 'pyf', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Papua New Guinea', 'pg', 'png', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Philippines', 'ph', 'phl', 'M', 'DMY', '12');
INSERT INTO countries VALUES ('Pakistan', 'pk', 'pak', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Poland', 'pl', 'pol', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saint Pierre and Miquelon', 'pm', 'spm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Pitcairn', 'pn', 'pcn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Puerto Rico', 'pr', 'pri', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Palestinian Territory, Occupied', 'ps', 'pse', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Portugal', 'pt', 'prt', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Palau', 'pw', 'plw', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Paraguay', 'py', 'pry', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Qatar', 'qa', 'qat', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Reunion', 're', 'reu', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Romania', 'ro', 'rou', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Serbia', 'rs', 'srb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Russian Federation', 'ru', 'rus', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Rwanda', 'rw', 'rwa', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saudi Arabia', 'sa', 'sau', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Solomon Islands', 'sb', 'slb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Seychelles', 'sc', 'syc', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Sudan', 'sd', 'sdn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Sweden', 'se', 'swe', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Singapore', 'sg', 'sgp', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saint Helena, Ascension and Tristan Da Cunha', 'sh', 'shn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Slovenia', 'si', 'svn', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Svalbard and Jan Mayen', 'sj', 'sjm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Slovakia', 'sk', 'svk', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Sierra Leone', 'sl', 'sle', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('San Marino', 'sm', 'smr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Senegal', 'sn', 'sen', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Somalia', 'so', 'som', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Suriname', 'sr', 'sur', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('South Sudan', 'ss', 'ssd', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Sao Tome and Principe', 'st', 'stp', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('El Salvador', 'sv', 'slv', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Sint Maarten (Dutch Part)', 'sx', 'sxm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Syrian Arab Republic', 'sy', 'syr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Swaziland', 'sz', 'swz', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Turks and Caicos Islands', 'tc', 'tca', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Chad', 'td', 'tcd', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('French Southern Territories', 'tf', '', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Togo', 'tg', 'tgo', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Thailand', 'th', 'tha', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Tajikistan', 'tj', 'tjk', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Tokelau', 'tk', 'tkl', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Timor-Leste', 'tl', 'tls', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Turkmenistan', 'tm', 'tkm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Tunisia', 'tn', 'tun', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Tonga', 'to', 'ton', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Turkey', 'tr', 'tur', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Trinidad and Tobago', 'tt', 'tto', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Tuvalu', 'tv', 'tuv', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Taiwan, Province of China', 'tw', '', 'M', 'YMD', '24');
INSERT INTO countries VALUES ('Tanzania, United Republic of', 'tz', 'tza', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Ukraine', 'ua', 'ukr', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Uganda', 'ug', 'uga', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('United States Minor Outlying Islands', 'um', '', 'I', 'MDY', '12');
INSERT INTO countries VALUES ('United States', 'us', 'usa', 'I', 'MDY', '12');
INSERT INTO countries VALUES ('Uruguay', 'uy', 'ury', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Uzbekistan', 'uz', 'uzb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Holy See (Vatican City State)', 'va', 'vat', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Saint Vincent and The Grenadines', 'vc', 'vct', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Venezuela, Bolivarian Republic of', 've', 'ven', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Virgin Islands, British', 'vg', 'vgb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Virgin Islands, U.S.', 'vi', 'vir', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Viet Nam', 'vn', 'vnm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Vanuatu', 'vu', 'vut', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Wallis and Futuna', 'wf', 'wlf', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Samoa', 'ws', 'wsm', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Yemen', 'ye', 'yem', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Mayotte', 'yt', 'myt', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('South Africa', 'za', 'zaf', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Zambia', 'zm', 'zmb', 'M', 'DMY', '24');
INSERT INTO countries VALUES ('Zimbabwe', 'zw', 'zwe', 'M', 'DMY', '24');

